; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Sun Oct 11 2020 12:47:10 GMT-0700 (Pacific Daylight Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation
G30 P0 X120 Y380 Z-99999 		; Probe near back lead screw
G30 P1 X00 Y95 Z-99999			; Probe near front left lead screw
G30 P2 X280 Y95 Z-99999 S3		; Probe near front right lead screw and calibrate 3 motors
G1 X0 Y0 F10000				; Home X and Y


