; tpost1.g
; called after tool 1 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Sun Oct 11 2020 12:47:10 GMT-0700 (Pacific Daylight Time)
; Wait for set temperatures to be reached
M116 P1

