; sleep.g
;!<summary> called when M1 (Sleep) is being processed. Currently there are no commands in this file and we need to learm why M1 would be called and then add any commands we think are appropriate. Maybe shut off all heaters and fans, disable steppers?</summary>
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Sun Oct 11 2020 12:47:10 GMT-0700 (Pacific Daylight Time)

